In [2]:
import numpy as np
import math
import random

In [3]:
class TicTacToe():
    def __init__(self):
        self.board=self.reset()
        self.winner=None
    def reset(self):
        self.board=[0]*9
        return self.board
    def showBoard(self):
         print(np.array(self.board).reshape(3,3))
    @staticmethod
    def showPos():
        return np.array([x for x in range(9)]).reshape(3,3)
    def makeMove(self,pos,player):
        if self.board[pos]==0:
            self.board[pos]=player
            if self.isWinner(pos,player):
                self.winner=player
            return True
        return False
    def isWinner(self,pos,player):
        row_ind = math.floor(pos / 3)
        row = self.board[row_ind*3:(row_ind+1)*3]
        if all([s == player for s in row]):
            return True
        col_ind = pos % 3
        column = [self.board[col_ind+i*3] for i in range(3)]
        if all([s == player for s in column]):
            return True
        if pos % 2 == 0:
            diagonal1 = [self.board[i] for i in [0, 4, 8]]
            if all([s == player for s in diagonal1]):
                return True
            diagonal2 = [self.board[i] for i in [2, 4, 6]]
            if all([s == player for s in diagonal2]):
                return True
        return False
    def emptyCount(self):
        return self.board.count(0)
    def isEmptySquare(self):
        return 0 in self.board
    def availableMoves(self):
        return [i for i, x in enumerate(self.board) if x==0]

In [4]:
# t=TicTacToe()
# print(t.reset())
# print(t.showPos())
# p=1
# for i in range(9):
#     n=int(input("Enter a pos "))
#     print("Is move valid: ",t.makeMove(n,p))
#     print("The Board is: \n",t.showBoard())
#     print("Name of the winner: ", t.winner)
#     print("isEmptySquares", t.isEmptySquare())
#     print("numEmptySquares", t.emptyCount())
#     print("availableMoves", t.availableMoves())
#     p*=-1

In [5]:
def play(ttt,X,O):
    print(ttt.showPos())
    player=1
    while ttt.isEmptySquare():
        if player==1:
            pos=X.getMove(ttt)
        else:
            pos=O.getMove(ttt)
        if ttt.makeMove(pos,player):
            print("legal moves are: ",ttt.availableMoves())
            print(ttt.showBoard())
        if ttt.winner:
            print("Result: "+ str(player) +' wins')
            return player
        player*=-1
    print("Result: Tie")

In [10]:
class Player():
    def __init__(self, letter):
        self.letter = letter

    def getMove(self, game):
        pass

class Manual(Player):
    def __init__(self, letter):
        super().__init__(letter)

    def getMove(self, game):
        valid_square = False
        val = None
        while not valid_square:
            square = int(input('Enter pos : '))
            try:
                pos = square
                if pos not in game.availableMoves():
                    raise ValueError
                valid_square = True
            except ValueError:
                print('Invalid input...Please try again.')
        return pos
class RandomMoveGenerator(Player):
    def __init__(self, letter):
        super().__init__(letter)

    def getMove(self, game):
        pos = random.choice(game.availableMoves())
        return pos

class AI(Player):
    def __init__(self, letter):
        super().__init__(letter)

    def getMove(self, game):
        if self.letter=='X':
            p=1
        else:
            p=-1
        if len(game.availableMoves()) == 9:
            pos = random.choice(game.availableMoves())
        else:
            pos = self.minimax(game, p)['position']
        return pos

    def minimax(self, state, p):
        mp=1 if self.letter == 'X' else -1
        op=-1 if p==1 else 1
        if state.winner == op:
            if op == mp:
                return {'position': None, 'score': 1 * (state.emptyCount() + 1)}
            else:
                return {'position': None, 'score': -1 * (state.emptyCount() + 1)}
            
        elif not state.isEmptySquare():
            return {'position': None, 'score': 0}
        if p == mp:
            best = {'position': None, 'score': -math.inf} 
        else:
            best = {'position': None, 'score': math.inf} 
        for move in state.availableMoves():
            state.makeMove(move, p)
            score=self.minimax(state, op)
            state.board[move] = 0
            state.winner=None
            score['position']=move 
            if p == mp:
                if score['score'] > best['score']:
                    best = score
            else:
                if score['score'] < best['score']:
                    best = score
        return best

In [11]:
if __name__ == '__main__':
    count=0
    icount=0
    n=100
    for i in range(n):
        X = RandomMoveGenerator('X')
        O = AI('O')
        t = TicTacToe()
        x=play(t, X, O)
        if x==-1:count+=1
        if x==1: icount+=1
    print("ai wins: ",count)
    print("draws: ", n-icount-count)
    print("ai loses: ", icount)
    

[[0 1 2]
 [3 4 5]
 [6 7 8]]
legal moves are:  [0, 1, 2, 3, 4, 5, 6, 7]
[[0 0 0]
 [0 0 0]
 [0 0 1]]
None
legal moves are:  [0, 1, 2, 3, 5, 6, 7]
[[ 0  0  0]
 [ 0 -1  0]
 [ 0  0  1]]
None
legal moves are:  [0, 1, 3, 5, 6, 7]
[[ 0  0  1]
 [ 0 -1  0]
 [ 0  0  1]]
None
legal moves are:  [0, 1, 3, 6, 7]
[[ 0  0  1]
 [ 0 -1 -1]
 [ 0  0  1]]
None
legal moves are:  [0, 3, 6, 7]
[[ 0  1  1]
 [ 0 -1 -1]
 [ 0  0  1]]
None
legal moves are:  [0, 6, 7]
[[ 0  1  1]
 [-1 -1 -1]
 [ 0  0  1]]
None
Result: -1 wins
[[0 1 2]
 [3 4 5]
 [6 7 8]]
legal moves are:  [0, 1, 2, 3, 4, 5, 7, 8]
[[0 0 0]
 [0 0 0]
 [1 0 0]]
None
legal moves are:  [0, 1, 2, 3, 5, 7, 8]
[[ 0  0  0]
 [ 0 -1  0]
 [ 1  0  0]]
None
legal moves are:  [0, 1, 2, 3, 5, 7]
[[ 0  0  0]
 [ 0 -1  0]
 [ 1  0  1]]
None
legal moves are:  [0, 1, 2, 3, 5]
[[ 0  0  0]
 [ 0 -1  0]
 [ 1 -1  1]]
None
legal moves are:  [0, 1, 2, 5]
[[ 0  0  0]
 [ 1 -1  0]
 [ 1 -1  1]]
None
legal moves are:  [0, 2, 5]
[[ 0 -1  0]
 [ 1 -1  0]
 [ 1 -1  1]]
None
Result: -1 wins


In [ ]:
''' 
Out of 100: 
ai wins:  87
draws:  13
ai loses:  0
'''